### ISSUE TITLE
about python implementation on kd-tree

### ISSUE THREAD

**Issue by amiltonwong** [mlarocca/AlgorithmsAndDataStructuresInAction#3]
Hi, @mlarocca ,

I'm studying your book "Algorithms and Data Structures in Action". When would you release the python implementation on kd-tree?

THX!

**Comment by mlarocca** [comment]
Hi @amiltonwong!
Thanks for your question, and for reading "Algorithms and Data Structures in Action": I hope you are finding it interesting!

For what concerns k-d trees, at the moment there is no ETA for adding a Python implementation to our repo. Although my personal long term goal is implementing all the data structures in the book in most of the mainstream languages, this is not planned as part of the book. 
For this book, in fact, we chose to use pseudo-code and not any specific language, to make the content accessible to the largest audience possible.

For k-d trees, we decided to initially stick with a JavaScript implementation; Python felt better covered, considering that you can use, for instance, Scipy's [implementation](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.spatial.KDTree.html).
If you are interested in checking out how it's used, I myself resorted to Scipy's version in a couple of notebooks on this repo, for instance here: https://github.com/mlarocca/AlgorithmsAndDataStructuresInAction/blob/master/Python/mlarocca/notebooks/k_means.ipynb

You can also check out Scipy's implementation [here](https://github.com/scipy/scipy/blob/master/scipy/spatial/kdtree.py)
Naturally, this implementation is more concerned about efficiency...

Cheers!
